backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use yii\web\Controller;

class SiteController extends Controller
{
	/**
	 * @inheritdoc
	 */
	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;

/**
 * Site controller
 */
class SiteController extends Controller
{
	/**
	 * @inheritdoc
	 */
	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}

	/**
	 * Displays homepage.
	 *
	 * @return mixed
	 */
	public function actionIndex()
	{
		return $this->render('index');
	}

	/**
	 * Displays download page.
	 *
	 * @return mixed
	 */
	public function actionDownloadWorker() {
		return $this->render('download');
	}

	/**
	 * Displays support page.
	 *
	 * @return mixed
	 */
	public function actionSupport()
	{
		return $this->render('support');
	}

	/**
	 * Displays order page.
	 *
	 * @return mixed
	 */
	public function actionOrder() {
		return $this->render('order');
	}
}

frontend/views/site/download.php
<?php

use yii\helpers\Url;
use frontend\widgets\Download;

/**
 * @var yii\web\View $this
 */

$params = Yii::$app->params;

$this->registerMetaTag([
	'property' => 'og:type',
	'content' => 'website',
]);

$url = Url::toRoute(['site/download-worker'], true);

$this->registerMetaTag([
	'property' => 'og:url',
	'content' => $url,
]);

$this->registerLinkTag([
	'rel' => 'canonical',
	'href' => $url,
]);

$this->registerMetaTag([
	'property' => 'og:image',
	'content' => Url::to('@web/styles/worker-logo.png', true),
]);

$this->registerMetaTag([
	'property' => 'og:title',
	'content' => $params['mainOgTitle'],
]);

$this->registerMetaTag([
	'name' => 'description',
	'content' => $params['mainMetaDescription'],
]);

$this->registerMetaTag([
	'property' => 'og:description',
	'content' => $params['mainOgDescription'],
]);

$this->registerMetaTag([
	'name' => 'keywords',
	'content' => $params['mainKeywords'],
]);

$this->title = 'Скачать';
?>
<div class="download-page site-page" id="download-page">
	<div class="narrow">
		<h1><?= $this->title ?></h1>
		<?= Download::widget([
			'isModal' => false,
		]); ?>
	</div>
</div>

frontend/views/site/error.php
<?php

use \common\helpers\Html;
use \yii\web\NotFoundHttpException;
use \yii\web\ForbiddenHttpException;

/**
 * @var $this yii\web\View
 * @var $name string
 * @var $message string
 * @var $exception Exception
 */

$this->title = $message;
?>
<div class="site-page error-page">
    <div class="narrow">
        <h1><?= Html::encode($this->title); ?></h1>
        <p>
            <?php
            if ($exception instanceof NotFoundHttpException) {
                ?>Вы можете перейти на главную или найти её самостоятельно.<?php
            } elseif ($exception instanceof ForbiddenHttpException) {
                ?>Войдите под аккаунтом, имеющим такие права.<?php
            } else {
                ?>Мы уже работаем над исправлением ошибки.<?php
            }
            ?>
        </p>
    </div>
</div>

frontend/views/site/order.php
<?php

use yii\helpers\Url;
use frontend\widgets\Order;

/**
 * @var yii\web\View $this
 */

$params = Yii::$app->params;

$this->registerMetaTag([
	'property' => 'og:type',
	'content' => 'website',
]);

$url = Url::toRoute(['site/order'], true);

$this->registerMetaTag([
	'property' => 'og:url',
	'content' => $url,
]);

$this->registerLinkTag([
	'rel' => 'canonical',
	'href' => $url,
]);

$this->registerMetaTag([
	'property' => 'og:image',
	'content' => Url::to('@web/styles/worker-logo.png', true),
]);

$this->registerMetaTag([
	'property' => 'og:title',
	'content' => $params['mainOgTitle'],
]);

$this->registerMetaTag([
	'name' => 'description',
	'content' => $params['mainMetaDescription'],
]);

$this->registerMetaTag([
	'property' => 'og:description',
	'content' => $params['mainOgDescription'],
]);

$this->registerMetaTag([
	'name' => 'keywords',
	'content' => $params['mainKeywords'],
]);

$this->title = 'Купить';
?>
<div class="order-page site-page" id="order-page">
	<div class="narrow">
		<h1><?= $this->title ?></h1>
		<?= Order::widget([
			'isModal' => false,
		]); ?>
	</div>
</div>

frontend/views/site/support.php
<?php

use yii\helpers\Url;
use frontend\widgets\Support;

/**
 * @var yii\web\View $this
 */

$params = Yii::$app->params;

$this->registerMetaTag([
	'property' => 'og:type',
	'content' => 'website',
]);

$url = Url::toRoute(['site/support'], true);

$this->registerMetaTag([
	'property' => 'og:url',
	'content' => $url,
]);

$this->registerLinkTag([
	'rel' => 'canonical',
	'href' => $url,
]);

$this->registerMetaTag([
	'property' => 'og:image',
	'content' => Url::to('@web/styles/worker-logo.png', true),
]);

$this->registerMetaTag([
	'property' => 'og:title',
	'content' => $params['mainOgTitle'],
]);

$this->registerMetaTag([
	'name' => 'description',
	'content' => $params['mainMetaDescription'],
]);

$this->registerMetaTag([
	'property' => 'og:description',
	'content' => $params['mainOgDescription'],
]);

$this->registerMetaTag([
	'name' => 'keywords',
	'content' => $params['mainKeywords'],
]);

$this->title = 'Поддержка';
?>
<div class="support-page site-page" id="support-page">
	<div class="narrow">
		<h1><?= $this->title ?></h1>
		<?= Support::widget([
			'isModal' => false,
		]); ?>
	</div>
</div>